//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2006-2021 VMware, Inc.
// SPDX-License-Identifier: MIT

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"github.com/vmware-tanzu-labs/namespace-operator/apis/common"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TanzuNamespace) DeepCopyInto(out *TanzuNamespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TanzuNamespace.
func (in *TanzuNamespace) DeepCopy() *TanzuNamespace {
	if in == nil {
		return nil
	}
	out := new(TanzuNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TanzuNamespace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TanzuNamespaceList) DeepCopyInto(out *TanzuNamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TanzuNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TanzuNamespaceList.
func (in *TanzuNamespaceList) DeepCopy() *TanzuNamespaceList {
	if in == nil {
		return nil
	}
	out := new(TanzuNamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TanzuNamespaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TanzuNamespaceSpec) DeepCopyInto(out *TanzuNamespaceSpec) {
	*out = *in
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TanzuNamespaceSpec.
func (in *TanzuNamespaceSpec) DeepCopy() *TanzuNamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(TanzuNamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TanzuNamespaceSpecResources) DeepCopyInto(out *TanzuNamespaceSpecResources) {
	*out = *in
	out.Limits = in.Limits
	out.Requests = in.Requests
	out.Max = in.Max
	out.Quota = in.Quota
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TanzuNamespaceSpecResources.
func (in *TanzuNamespaceSpecResources) DeepCopy() *TanzuNamespaceSpecResources {
	if in == nil {
		return nil
	}
	out := new(TanzuNamespaceSpecResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TanzuNamespaceSpecResourcesLimits) DeepCopyInto(out *TanzuNamespaceSpecResourcesLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TanzuNamespaceSpecResourcesLimits.
func (in *TanzuNamespaceSpecResourcesLimits) DeepCopy() *TanzuNamespaceSpecResourcesLimits {
	if in == nil {
		return nil
	}
	out := new(TanzuNamespaceSpecResourcesLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TanzuNamespaceSpecResourcesMax) DeepCopyInto(out *TanzuNamespaceSpecResourcesMax) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TanzuNamespaceSpecResourcesMax.
func (in *TanzuNamespaceSpecResourcesMax) DeepCopy() *TanzuNamespaceSpecResourcesMax {
	if in == nil {
		return nil
	}
	out := new(TanzuNamespaceSpecResourcesMax)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TanzuNamespaceSpecResourcesQuota) DeepCopyInto(out *TanzuNamespaceSpecResourcesQuota) {
	*out = *in
	out.Requests = in.Requests
	out.Limits = in.Limits
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TanzuNamespaceSpecResourcesQuota.
func (in *TanzuNamespaceSpecResourcesQuota) DeepCopy() *TanzuNamespaceSpecResourcesQuota {
	if in == nil {
		return nil
	}
	out := new(TanzuNamespaceSpecResourcesQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TanzuNamespaceSpecResourcesQuotaLimits) DeepCopyInto(out *TanzuNamespaceSpecResourcesQuotaLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TanzuNamespaceSpecResourcesQuotaLimits.
func (in *TanzuNamespaceSpecResourcesQuotaLimits) DeepCopy() *TanzuNamespaceSpecResourcesQuotaLimits {
	if in == nil {
		return nil
	}
	out := new(TanzuNamespaceSpecResourcesQuotaLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TanzuNamespaceSpecResourcesQuotaRequests) DeepCopyInto(out *TanzuNamespaceSpecResourcesQuotaRequests) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TanzuNamespaceSpecResourcesQuotaRequests.
func (in *TanzuNamespaceSpecResourcesQuotaRequests) DeepCopy() *TanzuNamespaceSpecResourcesQuotaRequests {
	if in == nil {
		return nil
	}
	out := new(TanzuNamespaceSpecResourcesQuotaRequests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TanzuNamespaceSpecResourcesRequests) DeepCopyInto(out *TanzuNamespaceSpecResourcesRequests) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TanzuNamespaceSpecResourcesRequests.
func (in *TanzuNamespaceSpecResourcesRequests) DeepCopy() *TanzuNamespaceSpecResourcesRequests {
	if in == nil {
		return nil
	}
	out := new(TanzuNamespaceSpecResourcesRequests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TanzuNamespaceStatus) DeepCopyInto(out *TanzuNamespaceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]common.PhaseCondition, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]common.Resource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TanzuNamespaceStatus.
func (in *TanzuNamespaceStatus) DeepCopy() *TanzuNamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(TanzuNamespaceStatus)
	in.DeepCopyInto(out)
	return out
}
