---
name: Lint
on:
  - push
  - pull_request
jobs:
  go-lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  docker-lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hadolint
        uses: brpaz/hadolint-action@v1.2.1
  
  yaml-lint:
    name: Yaml Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: yaml lint
      uses: ibiqlik/action-yamllint@v3.0.0    

  check-license-lines:
    runs-on: ubuntu-latest
    name: Check License Files
    steps:
    - uses: actions/checkout@master
    - name: Check License Lines
      uses: kt3k/license_checker@v1.0.6

  # go-test:
  #  name: Go Test
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: actions/setup-go@v2
  #      with:
  #        go-version: 1.16.x
  #    - name: Install KubeBuilder
  #      uses: RyanSiu1995/kubebuilder-action@v1.1
  #    - name: go test
  #     run: make test
