---
name: Publish
on:
  push:
    tags:
      - "v*"
jobs:
  publish-to-harbor:
    name: Publish To GitLab Registry
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    env:
      DOCKER_CONFIG: "${HOME}/.docker/"
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v2
      - name: Create Authentication
        run: mkdir -p ${DOCKER_CONFIG} && echo "{\"auths\":{\"${{ secrets.DOCKER_REGISTRY }}\":{\"username\":\"${{ secrets.DOCKER_USERNAME }}\",\"password\":\"${{ secrets.DOCKER_PASSWORD }}\"}}}" > ${DOCKER_CONFIG}config.json
      # - name: Setup Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # - name: Generate Tag List
      #   id: meta
      #   uses: crazy-max/ghaction-docker-meta@v2
      #   with:
      #     images: |
      #       ${{ secrets.DOCKER_REGISTRY }}/namespace_operator/namespace-operator
      #     tags: |
      #       type=ref,event=tag
      #       type=raw,value=latest
      # - name: Login to Harbor
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ${{ secrets.DOCKER_REGISTRY }}
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Publish to Harbor
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     context: .
      #     tags: |
      #       ${{ steps.meta.outputs.tags }}

      # - name: Publish Tag to Harbor
      #   uses: docker/build-push-action@v2
      #   with:
      #     registry: ${{ secrets.DOCKER_REGISTRY }}
      #     repository: namespace_operator/namespace-operator
      #     tag_with_ref: true
      # - name: Publish Latest to Harbor
      #   uses: docker/build-push-action@v1
      #   with:
      #     registry: ${{ secrets.DOCKER_REGISTRY }}
      #     repository: namespace_operator/namespace-operator
      #     tags: latest
      - name: Publish to GitLab Registry
        uses: aevea/action-kaniko@v0.6.1
        with:
          # Docker registry where the image will be pushed
          registry: ${{ secrets.DOCKER_REGISTRY }}
          # Username used for authentication to the Docker registry
          username: ${{ secrets.DOCKER_USERNAME }}
          # Password used for authentication to the Docker registry
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Image name
          image: ${{ secrets.DOCKER_REGISTRY}}/vmware-tanzu-labs/namespace-operator/namespace-operator
          # Tags the built image with additional latest tag
          tag_with_latest: true
