---
name: Publish
on:
  push:
    tags:
      - "v*"
jobs:
  publish-to-harbor:
    name: Publish To Harbor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Harbor
        uses: aevea/action-kaniko@v0.6.1
        with:
          # Docker registry where the image will be pushed
          registry: ${{ secrets.DOCKER_REGISTRY }}
          # Username used for authentication to the Docker registry
          username: ${{ secrets.DOCKER_USERNAME }}
          # Password used for authentication to the Docker registry
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Image name
          image: ${{ secrets.DOCKER_REGISTRY}}/namespace_operator/namespace-operator
          # Tags the built image with additional latest tag
          tag_with_latest: true
          env:
            DOCKER_CONFIG: /root/.docker/
